### ISSUE TITLE
IllegalArgumentException in ADAL authentication on Android 4.1x 

### ISSUE THREAD

**Issue by 1gravity** [AzureAD/azure-activedirectory-library-for-android#571]
When trying to authenticate (first time, interactive) for an ADAL account, the app crashes with the following exception:

> 
> E/AndroidRuntime( 5976): FATAL EXCEPTION: pool-5-thread-1
> E/AndroidRuntime( 5976): java.lang.IllegalArgumentException: rawBytes
> E/AndroidRuntime( 5976):        at com.microsoft.aad.adal.StorageHelper.getSecretKey(StorageHelper.java:211)
> E/AndroidRuntime( 5976):        at com.microsoft.aad.adal.StorageHelper.loadSecretKeyForAPI(StorageHelper.java:165)
> E/AndroidRuntime( 5976):        at com.microsoft.aad.adal.StorageHelper.encrypt(StorageHelper.java:319)
> E/AndroidRuntime( 5976):        at com.microsoft.aad.adal.DefaultTokenCacheStore.encrypt(DefaultTokenCacheStore.java:113)
> E/AndroidRuntime( 5976):        at com.microsoft.aad.adal.DefaultTokenCacheStore.setItem(DefaultTokenCacheStore.java:179)
> E/AndroidRuntime( 5976):        at com.microsoft.aad.adal.AuthenticationContext.setItemToCacheForUser(AuthenticationContext.java:1717)
> E/AndroidRuntime( 5976):        at com.microsoft.aad.adal.AuthenticationContext.setItemToCache(AuthenticationContext.java:1697)
> E/AndroidRuntime( 5976):        at com.microsoft.aad.adal.AuthenticationContext.access$300(AuthenticationContext.java:62)
> E/AndroidRuntime( 5976):        at com.microsoft.aad.adal.AuthenticationContext$5.run(AuthenticationContext.java:913)
> E/AndroidRuntime( 5976):        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1076)
> E/AndroidRuntime( 5976):        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:569)
> E/AndroidRuntime( 5976):        at java.lang.Thread.run(Thread.java:856)

This happens on Android 4.1x only (I tested on a Samsung Galaxy S2 and a Samsung Note II), it works on any other device I tested so far.

**Comment by weijjia** [comment]
We require the calling app to pass us secret key for data encryption for API version below 18

**Comment by 1gravity** [comment]
What secret key are you referring to?

**Comment by 1gravity** [comment]
Since there's not a lot of documentation on this ("If you want to use ADAL for lower SDK versions, you need to provide secret key at AuthenticationSettings.INSTANCE.setSecretKey" is about all I could find), here's what I did. Maybe you can incorporate this in the documentation:

```
    if (! Helper.isJellyBeanMR2OrHigher()) {
        // we need to provide a secret key on Android 4.2 and lower
        byte[] secretKey = getSecretKey();
        AuthenticationSettings.INSTANCE.setSecretKey(secretKey);
    }

    private byte[] getSecretKey() {
        String seed = getSeed();
        try {
            KeyGenerator keygen = KeyGenerator.getInstance("AES");
            SecureRandom secrand = SecureRandom.getInstance("SHA1PRNG", "Crypto");
            secrand.setSeed(seed.getBytes());
            keygen.init(256, secrand);
            SecretKey secKey = keygen.generateKey();
            return secKey.getEncoded();
        }
        catch (NoSuchAlgorithmException | NoSuchProviderException e) {
            // in this case we simply use the seed as secret key
            return seed.getBytes();
        }
    }

    private String getSeed() {
        // read the seed from the SharedPreferences
        String seed = Preferences.getString(Setting.CLOUD_SYNC_SEED4ONEDRIVE);
        if (seed.isEmpty()) {
            seed = getUniqueString(32);
            // save the seed in the SharedPreferences
            Preferences.putString(Setting.CLOUD_SYNC_SEED4ONEDRIVE, seed, true);
        }
        return seed;
    }

    private static final String AB = "0123456789ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz";
    private static Random rnd = new Random();

    private String getUniqueString(int len){
        StringBuilder sb = new StringBuilder( len );
        for( int i = 0; i < len; i++ ) {
            sb.append(AB.charAt(rnd.nextInt(AB.length())));
        }
        return sb.toString();
    }

```

**Comment by weijjia** [comment]
@1gravity We're working on a sample as well as instruction for supplying secret key.

**Comment by addev-ashish** [comment]
@weijjia Looks like this issue was resolved.

**Comment by nymerias** [comment]
We're seeing this exception on Android 6.01 device crashes: 

java.lang.IllegalArgumentException: rawBytes
	at com.microsoft.aad.adal.StorageHelper.getSecretKey(StorageHelper.java:505)
	at com.microsoft.aad.adal.StorageHelper.getKey(StorageHelper.java:383)
	at com.microsoft.aad.adal.StorageHelper.loadSecretKeyForDecryption(StorageHelper.java:335)
	at com.microsoft.aad.adal.StorageHelper.decrypt(StorageHelper.java:260)
	at com.microsoft.aad.adal.DefaultTokenCacheStore.decrypt(DefaultTokenCacheStore.java:136)
	at com.microsoft.aad.adal.DefaultTokenCacheStore.getItem(DefaultTokenCacheStore.java:155)
	at com.microsoft.aad.adal.TokenCacheAccessor.getRegularRefreshTokenCacheItem(TokenCacheAccessor.java:89)
	at com.microsoft.aad.adal.TokenCacheAccessor.getATFromCache(TokenCacheAccessor.java:62)
	at com.microsoft.aad.adal.AcquireTokenSilentHandler.getAccessToken(AcquireTokenSilentHandler.java:100)
	at com.microsoft.aad.adal.AcquireTokenRequest.tryAcquireTokenSilentLocally(AcquireTokenRequest.java:317)
	at com.microsoft.aad.adal.AcquireTokenRequest.acquireTokenSilentFlow(AcquireTokenRequest.java:285)
	at com.microsoft.aad.adal.AcquireTokenRequest.tryAcquireTokenSilent(AcquireTokenRequest.java:240)
	at com.microsoft.aad.adal.AcquireTokenRequest.performAcquireTokenRequest(AcquireTokenRequest.java:224)
	at com.microsoft.aad.adal.AcquireTokenRequest.access$200(AcquireTokenRequest.java:44)
	at com.microsoft.aad.adal.AcquireTokenRequest$1.run(AcquireTokenRequest.java:103)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1113)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:588)
	at java.lang.Thread.run(Thread.java:818)

**Comment by jaredsburrows** [comment]
@nazukj @addev-ashish My team is still seeing this a lot as well.

**Comment by addev-ashish** [comment]
@jaredsburrows @nymerias does this article help?
https://github.com/AzureAD/azure-activedirectory-library-for-android/wiki/Common-Issues-With-AndroidKeyStore

**Comment by jaredsburrows** [comment]
@addev-ashish @nazukj Not really. What is the fix?
