### ISSUE TITLE
ADAL Crash with Don't Keep Activities Enabled

### ISSUE THREAD

**Issue by joakley-msft** [AzureAD/azure-activedirectory-library-for-android#697]
ADAL can crash with the following stack when Don't Keep Activities is enabled in develop options, although since that setting is intended to simulate real low-memory conditions it could occur in actual usage. It appears that ADAL code is trying to operate on a UI element which is no longer valid (presumably because the activity has been removed). 

Our repro involves internal code; please contact me internally if you need a full repro environment.

08-04 15:13:28.013 3349-3349/? W/System.err: java.lang.IllegalArgumentException: View=com.android.internal.policy.impl.PhoneWindow$DecorView{d296d5f V.E..... R......D 0,0-321,174} not attached to window manager
08-04 15:13:28.013 3349-3349/? W/System.err:     at android.view.WindowManagerGlobal.findViewLocked(WindowManagerGlobal.java:386)
08-04 15:13:28.013 3349-3349/? W/System.err:     at android.view.WindowManagerGlobal.removeView(WindowManagerGlobal.java:312)
08-04 15:13:28.013 3349-3349/? W/System.err:     at android.view.WindowManagerImpl.removeViewImmediate(WindowManagerImpl.java:84)
08-04 15:13:28.013 3349-3349/? W/System.err:     at android.app.Dialog.dismissDialog(Dialog.java:341)
08-04 15:13:28.013 3349-3349/? W/System.err:     at android.app.Dialog.dismiss(Dialog.java:324)
08-04 15:13:28.013 3349-3349/? W/System.err:     at com.microsoft.aad.adal.AuthenticationActivity.displaySpinner(AuthenticationActivity.java:740)
08-04 15:13:28.014 3349-3349/? W/System.err:     at com.microsoft.aad.adal.AuthenticationActivity.access$1300(AuthenticationActivity.java:75)
08-04 15:13:28.014 3349-3349/? W/System.err:     at com.microsoft.aad.adal.AuthenticationActivity$CustomWebViewClient.showSpinner(AuthenticationActivity.java:643)
08-04 15:13:28.014 3349-3349/? W/System.err:     at com.microsoft.aad.adal.BasicWebViewClient.onPageFinished(BasicWebViewClient.java:147)
08-04 15:13:28.014 3349-3349/? W/System.err:     at com.android.webview.chromium.WebViewContentsClientAdapter.onPageFinished(WebViewContentsClientAdapter.java:495)
08-04 15:13:28.014 3349-3349/? W/System.err:     at com.android.org.chromium.android_webview.AwContentsClient$AwWebContentsObserver.didFinishLoad(AwContentsClient.java:69)
08-04 15:13:28.014 3349-3349/? W/System.err:     at com.android.org.chromium.base.SystemMessageHandler.nativeDoRunLoopOnce(Native Method)
08-04 15:13:28.014 3349-3349/? W/System.err:     at com.android.org.chromium.base.SystemMessageHandler.handleMessage(SystemMessageHandler.java:28)
08-04 15:13:28.014 3349-3349/? W/System.err:     at android.os.Handler.dispatchMessage(Handler.java:102)
08-04 15:13:28.014 3349-3349/? W/System.err:     at android.os.Looper.loop(Looper.java:135)
08-04 15:13:28.014 3349-3349/? W/System.err:     at android.app.ActivityThread.main(ActivityThread.java:5221)
08-04 15:13:28.014 3349-3349/? W/System.err:     at java.lang.reflect.Method.invoke(Native Method)
08-04 15:13:28.014 3349-3349/? W/System.err:     at java.lang.reflect.Method.invoke(Method.java:372)
08-04 15:13:28.014 3349-3349/? W/System.err:     at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:899)
08-04 15:13:28.014 3349-3349/? W/System.err:     at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:694)

**Comment by weijjia** [comment]
Adding repro steps: 
The scenario in which it occurs is pretty uncommon and is as follows:

1.	Turn on the “Don’t Keep Activities” developer option
2.	Create one AuthenticationActivity through an interactive auth call
3.	Create a second AuthenticationActivity through an interactive call on top of the previous one
4.	Enter valid creds into the topmost activity

**Comment by addev-ashish** [comment]
Thanks for reporting the bug. Its fixed in release 1.12.0.

**Comment by joakley-msft** [comment]
The most common case seems to be fixed, but we're still seeing intermittent instances of this crash in our automation. If I can nail down exact repro steps, I'll reopen the bug.
